name: depo_management
description: Driver management system with reporting capabilities
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  pdf: ^3.10.4
  printing: ^5.11.0
  intl: ^0.19.0
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.2
  file_selector: ^1.0.3
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  sqflite_common_ffi: ^2.3.2

flutter:
  uses-material-design: true
